### ISSUE TITLE
Question: Why not memoize instead of a custom scu?

### ISSUE THREAD

**Issue by BerkeleyTrue** [flexport/reflective-bind#21]
I was pretty gung ho about this project initially, but the idea of monkey patching scu or having to refactor all my pure components is distasteful.

What I haven't seen reading through your blog post or the read me is why not use a memoizing function similar to reselect within the transform instead of adding hidden props and creating a custom shallow equals func?

I'd like to know whether this option was explored and if you encountered any issues that made you switch tracks to this approach.

Thanks and Happy Coding

**Comment by dounan** [comment]
That's a great question! We explored the caching option but the main issue we ran into is handling the case where a component is rendered multiple times. In this case picking the cache size is difficult. Reselect is able to solve this with mapStateToPropsFactory because they wrap your component with a HOC, but this option is not available to us unless we also inject a HOC in our transform. With reflective-bind we don't have to worry about managing caches and setting cache sizes, and it allows the library to cover more use cases.

**Comment by BerkeleyTrue** [comment]
@dounan Thanks for the explanation. That makes sense and is also not initially obvious.

Has the possibility of this plugin automatically adding the required SCU during compile been explored?

**Comment by dounan** [comment]
> Has the possibility of this plugin automatically adding the required SCU during compile been explored?

We haven't explored this option yet.

Internally we have a custom base component that allows us to turn the custom sCU on for all of the components that want to be pure. The `PureComponent` monkey patching approach could work to automatically get the desired behavior.

My gut feel is that automatically injecting custom sCU into components might be overreaching, but I am definitely open to any ideas you may have regarding this.

**Comment by BerkeleyTrue** [comment]
@dounan thanks for taking the time to answer my questions.

Happy Coding
